before_install:
- sudo apt-get update && sudo apt-get install texlive-latex-base texlive-latex-recommended
  texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended
script:
- pdflatex paper.tex
- bibtex paper
- pdflatex paper.tex
- pdflatex paper.tex
- if [ "$TRAVIS_BRANCH" == "master" ]; then bash ./deploy.sh; fi
env:
  global:
    GH_REF: github.com/spring-studio-2016/article.git
    secure: e2DdXiPmBjdSopFcncCH1gLwSSdeB70hYDq9l5lkKMjuwTjCgUIQxB/5peSkyR6vs00FSg/Z4d5M4bOth44sbjgA6cNAwIc623Jstb+VZ6xn6a2vlN1kOx9ii1unZUT64LWWAxjd17ncLROic2FtIg8ALX40fPUgW/sIGXNOw5KN1jzb1vv8/NJMqdVDbe/LrsAHOI1imdIo7OIVzu4iclXTRTIIAWN3egt5TcRhF1aQWm0cQpapb/gosKZgbacLMFMhtn8jTY/BbqBO05r3x2sr62YAykSoRHf1DtuhxGtgvhp8vI8IznOKh62W6aKVPdYax1/0wEVRH/hsDLkALybpIFlp3VeZHTd6p1jYKtFNctjPPI7CRYsE6IqMf4zF9jhgYu2By08V1OTGHybAxuWW9QQk751TMTst1VasHD/PbFQDrHLB18keKKDoybDigYGUF/jB9wxXQQMinKPA0Au6/oAe6MqBEQKqr7S6AJSlKVOa1esx0L4czLcqj6Vp32TpRYeD4YLeg7iLk6EeT6W7uHQmc7uNsuEQIqIYDRVznwlgilW5YCtYskff09GNwyD0NFPVwwgwYPB74IMwy8cT+KvsfHvEUmJfIT2wx0ubet68uPA65OiEi5lpHc1487ipcapbVBkDVn9DtybOPzDIMnLDgMfu3EXsBawlK2E=
notifications:
  slack:
    rooms:
      secure: oUlYbekffREYdOwB1hsgw1F70FE3IuIKVKJdb74ZUEm4BMaHIb+n5/6vhNZ43ji36hi+zYyxiIhFUwZ531toi5cItvjq/16ACUCYCf2bVmecNxczJNrqmmaLRBJP0vWIF8SPFAZt4Q2xZz9WiPhOs++yCrv3peMqa8Zhd5Ofgnvyz9cGtLb2iWaeR5fNis31+mOrCVkEWtDK93CtJwUaHm0MnZ09L922vtT7ftkoBnnfkZ2hqTdsObC7H2Xy2/61AB3qfQUOHM+yPjcXSlrgiNv2xB9ezvoiu3C9jbOuKcd73YdRUthRBwrpsLkTqKpc+j+v1LGXGsdOME0APjzLTOP4g+1JcK4izBql6RqIOksK2eE9ImJFucqE1ciHAeweu0S97KHpycBhC1uE/fM9fympW9FU3OZVCWVkWDWhgW/Cxspv/066XaSt0dztQrSRXLop7sLrhNyhIq/t3wdgamlVaIDCslZTutld2qE20pq87oHcpTZUVXS5JkHxv/3seFPV5RhiCcygXhP5ejRRkuDAIYvQnJRnc5Du9fKTKmJyps6eByP2iZ0pN/uf/OlNcBttAS1SDIg6iYS+qNPjiVY6ynQGJVlguR6e1WnK87uNM+DTKAGjSpsQ5Dd3bpdliOUGZHQuTfoBedISL9OxtRdfEwT6iymUXK/P8OCzphk=
